Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
