#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "fysk.y".
#

require 'racc/parser.rb'
module Fysk
  class Parser < Racc::Parser

module_eval(<<'...end fysk.y/module_eval...', 'fysk.y', 78)
require "strscan"

def parse(input)
  @scanner = StringScanner.new(input)

  do_parse
end

def next_token
  return p [false, "$"] if @scanner.eos?

  p case
  when v = @scanner.scan(/\A[ \t\f]*\//)
    [:ARGUMENT_DECLARATION_BEGIN_END, v.strip]
  when v = @scanner.scan(/\A\s*\./)
    [:LAMBDA_EXPRESSION_PERIOD, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*:/)
    [:DEFINITION_SYMBOL, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*'/)
    [:BINDING_SYMBOL, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*,/)
    [:COMMA, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*@/)
    [:FUNCTION_APPLICATION_SYMBOL, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*\+/)
    [:PLUS, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*-/)
    [:MINUS, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*\*/)
    [:MULTI, v.strip]
  when v = @scanner.scan(/\A[ \t\f]+div\b/)
    [:DIVIDE, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*\[/)
    [:ARRAY_BEGIN, v.strip]
  when v = @scanner.scan(/\A\s*\]/)
    [:ARRAY_END, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*[a-zA-Z_]\w*\b/)
    [:IDENT, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*"[^\r\n]*"/)
    [:STRING, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*\d+/)
    [:NUMBER, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*(?:true|false)/)
    [:BOOL, v.strip]
  when v = @scanner.scan(/\A[ \t\f]*[\r\n]+/)
    [:NEWLINE, v]
  when v = @scanner.scan(/\A\S*\b/)
    raise Racc::ParseError, "unknown token #{v.inspect}"
  end
end
...end fysk.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     9,    18,    21,    21,    16,    17,    51,    11,    12,    13,
    14,     9,    24,    25,    21,    16,    17,     9,    11,    12,
    13,    14,     9,    36,    32,    25,    16,    17,    56,    41,
    12,    13,    14,     9,    42,    24,    49,    16,    17,    51,
    11,    12,    13,    14,     9,    52,   -12,    21,    16,    17,
   nil,    11,    12,    13,    14,     9,   nil,   nil,   nil,    16,
    17,   nil,    11,    12,    13,    14,     9,   nil,   nil,   nil,
    16,    17,   nil,    41,    12,    13,    14,     9,   nil,   nil,
   nil,    16,    17,   nil,    11,    12,    13,    14,    17,   nil,
    46,    12,    13,    14,    17,   nil,    46,    12,    13,    14,
   -22,   -22,   -22,   -22,   -23,   -23,   -23,   -23,    29,    30,
    27,    28 ]

racc_action_check = [
     0,     1,     2,     8,     0,     0,    38,     0,     0,     0,
     0,    17,     9,    11,    38,    17,    17,    16,    17,    17,
    17,    17,    22,    18,    16,    41,    22,    22,    41,    22,
    22,    22,    22,    25,    23,    24,    34,    25,    25,    35,
    25,    25,    25,    25,    26,    37,    39,    56,    26,    26,
   nil,    26,    26,    26,    26,    50,   nil,   nil,   nil,    50,
    50,   nil,    50,    50,    50,    50,    53,   nil,   nil,   nil,
    53,    53,   nil,    53,    53,    53,    53,    60,   nil,   nil,
   nil,    60,    60,   nil,    60,    60,    60,    60,    31,   nil,
    31,    31,    31,    31,    48,   nil,    48,    48,    48,    48,
     4,     4,     4,     4,     7,     7,     7,     7,    15,    15,
    15,    15 ]

racc_action_pointer = [
    -7,     1,   -16,   nil,    98,   nil,   nil,   102,   -15,    -2,
   nil,     7,   nil,   nil,   nil,   106,    10,     4,    23,   nil,
   nil,   nil,    15,    27,    21,    26,    37,   nil,   nil,   nil,
   nil,    76,   nil,   nil,    23,    29,   nil,    37,    -4,    38,
   nil,    19,   nil,   nil,   nil,   nil,   nil,   nil,    82,   nil,
    48,   nil,   nil,    59,   nil,   nil,    29,   nil,   nil,   nil,
    70,   nil ]

racc_action_default = [
   -44,   -44,   -41,    -2,    -3,    -4,    -5,    -6,   -41,   -10,
   -16,   -17,   -18,   -19,   -20,   -44,   -44,   -37,   -44,    -1,
   -40,   -43,   -44,   -44,   -10,   -44,   -44,   -24,   -25,   -26,
   -27,   -33,   -30,   -31,   -44,   -36,    62,   -44,   -44,   -14,
   -13,   -17,    -8,    -9,   -28,   -21,   -17,   -29,   -33,   -34,
   -37,   -42,    -7,   -44,   -38,   -39,   -41,   -32,   -35,   -11,
   -44,   -15 ]

racc_goto_table = [
     2,    19,    34,    37,    48,    23,    47,    22,    50,     1,
    33,    54,    53,    26,    31,    55,   nil,   nil,   nil,   nil,
    43,    48,    39,    57,   nil,    44,    45,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    59,    58,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    39,   nil,    60,   nil,   nil,   nil,   nil,
    61 ]

racc_goto_check = [
     2,     3,    20,    10,     5,    11,    19,     3,    21,     1,
     4,    21,    13,    17,    18,    22,   nil,   nil,   nil,   nil,
    11,     5,     2,    19,   nil,     2,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    10,    20,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     2,   nil,     3,   nil,   nil,   nil,   nil,
     2 ]

racc_goto_pointer = [
   nil,     9,     0,    -1,    -6,   -27,   nil,   nil,   nil,   nil,
   -19,    -4,   nil,   -26,   nil,   nil,   nil,    -2,    -2,   -25,
   -15,   -27,   -23 ]

racc_goto_default = [
   nil,   nil,    35,   nil,     3,     4,     5,     6,     7,     8,
   nil,   nil,    38,   nil,    40,    10,    15,   nil,   nil,   nil,
   nil,   nil,    20 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 20, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  4, 23, :_reduce_7,
  3, 28, :_reduce_8,
  2, 30, :_reduce_9,
  0, 30, :_reduce_10,
  3, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  4, 33, :_reduce_15,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_20,
  3, 25, :_reduce_21,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  3, 26, :_reduce_28,
  3, 27, :_reduce_29,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  2, 38, :_reduce_none,
  0, 38, :_reduce_none,
  3, 34, :_reduce_none,
  3, 39, :_reduce_none,
  1, 39, :_reduce_none,
  0, 39, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  1, 22, :_reduce_none,
  0, 22, :_reduce_none,
  1, 40, :_reduce_42,
  1, 41, :_reduce_43 ]

racc_reduce_n = 44

racc_shift_n = 62

racc_token_table = {
  false => 0,
  :error => 1,
  :MULTI => 2,
  :DIVIDE => 3,
  :PLUS => 4,
  :MINUS => 5,
  :BINDING_SYMBOL => 6,
  :ARGUMENT_DECLARATION_BEGIN_END => 7,
  :LAMBDA_EXPRESSION_PERIOD => 8,
  :DEFINITION_SYMBOL => 9,
  :COMMA => 10,
  :FUNCTION_APPLICATION_SYMBOL => 11,
  :ARRAY_BEGIN => 12,
  :ARRAY_END => 13,
  :IDENT => 14,
  :STRING => 15,
  :NUMBER => 16,
  :BOOL => 17,
  :NEWLINE => 18 }

racc_nt_base = 19

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "MULTI",
  "DIVIDE",
  "PLUS",
  "MINUS",
  "BINDING_SYMBOL",
  "ARGUMENT_DECLARATION_BEGIN_END",
  "LAMBDA_EXPRESSION_PERIOD",
  "DEFINITION_SYMBOL",
  "COMMA",
  "FUNCTION_APPLICATION_SYMBOL",
  "ARRAY_BEGIN",
  "ARRAY_END",
  "IDENT",
  "STRING",
  "NUMBER",
  "BOOL",
  "NEWLINE",
  "$start",
  "program",
  "expression",
  "newline_or_null_separator",
  "lambda_expression",
  "unary_expression",
  "binary_expression",
  "binding",
  "function_application",
  "argument_declaration",
  "definition_or_expression_list",
  "argument_list",
  "definition_or_expression",
  "comma_or_newline_separator",
  "definition",
  "array",
  "binary_expression_left_operand",
  "binary_operator",
  "function",
  "function_application_parameter_list",
  "array_item_list",
  "comma_separator",
  "newline_separator" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'fysk.y', 28)
  def _reduce_7(val, _values, result)
     warn "lambda_expression found: #{val.map(&:inspect).join(' ')}"
    result
  end
.,.,

module_eval(<<'.,.,', 'fysk.y', 31)
  def _reduce_8(val, _values, result)
          warn "argument_declaration found. arguments:"
      while ident = @argument_list.pop
        warn ident
      end

    result
  end
.,.,

module_eval(<<'.,.,', 'fysk.y', 37)
  def _reduce_9(val, _values, result)
     @argument_list.push(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'fysk.y', 39)
  def _reduce_10(val, _values, result)
     @argument_list = []
    result
  end
.,.,

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'fysk.y', 44)
  def _reduce_15(val, _values, result)
     warn "definition found: #{val.map(&:inspect).join(' ')}"
    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'fysk.y', 47)
  def _reduce_20(val, _values, result)
     warn "unary_expression found: #{val.map(&:inspect).join(' ')}"
    result
  end
.,.,

module_eval(<<'.,.,', 'fysk.y', 50)
  def _reduce_21(val, _values, result)
     warn "binary_expression found: #{val.map(&:inspect).join(' ')}"
    result
  end
.,.,

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'fysk.y', 55)
  def _reduce_28(val, _values, result)
     warn "binding found: #{val.map(&:inspect).join(' ')}"
    result
  end
.,.,

module_eval(<<'.,.,', 'fysk.y', 58)
  def _reduce_29(val, _values, result)
     warn "function_application found: #{val.map(&:inspect).join(' ')}"
    result
  end
.,.,

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

module_eval(<<'.,.,', 'fysk.y', 71)
  def _reduce_42(val, _values, result)
     warn "comma_separator found"
    result
  end
.,.,

module_eval(<<'.,.,', 'fysk.y', 73)
  def _reduce_43(val, _values, result)
     warn "newline_separator found"
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Fysk
